ClientEvents.lang('en_us', event => {
    event.renameBlock('the_deep_void:onyx_ore', 'Void Onyx Ore')
    event.renameItem('the_deep_void:onyx_ore', 'Void Onyx Ore')
    event.renameBlock('the_deep_void:block_of_onyx', 'Void Onyx Block')
    event.renameItem('the_deep_void:block_of_onyx', 'Void Onyx Block')
    event.renameBlock('the_deep_void:block_of_refined_onyx', 'Refined Void Onyx Block')
    event.renameItem('the_deep_void:block_of_refined_onyx', 'Refined Void Onyx Block')
    event.renameBlock('the_deep_void:refined_onyx_slab', 'Refined Void Onyx Slab')
    event.renameItem('the_deep_void:refined_onyx_slab', 'Refined Void Onyx Slab')
    event.renameBlock('the_deep_void:refined_onyx_stairs', 'Refined Void Onyx Stairs')
    event.renameItem('the_deep_void:refined_onyx_stairs', 'Refined Void Onyx Stairs')
    
    event.renameItem('the_deep_void:onyx_armor_boots', 'Void Onyx Boots')
    event.renameItem('the_deep_void:onyx_armor_chestplate', 'Void Onyx Chestplate')
    event.renameItem('the_deep_void:onyx_armor_helmet', 'Void Onyx Helmet')
    event.renameItem('the_deep_void:onyx_armor_leggings', 'Void Onyx Leggings')
    event.renameItem('the_deep_void:onyx_axe', 'Void Onyx Axe')
    event.renameItem('the_deep_void:onyx_hoe', 'Void Onyx Hoe')
    event.renameItem('the_deep_void:onyx_needle', 'Void Onyx Needle')
    event.renameItem('the_deep_void:onyx_pickaxe', 'Void Onyx Pickaxe')
    event.renameItem('the_deep_void:onyx_shovel', 'Void Onyx Shovel')
    event.renameItem('the_deep_void:onyx_sword', 'Void Onyx Sword')
    event.renameItem('the_deep_void:refined_onyx', 'Refined Void Onyx')
    event.renameItem('the_deep_void:onyx', 'Void Onyx')
})